services:
  - type: web
    name: my-laravel-app
    runtime: node
    buildCommand: |
      npm install
      npm run build
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
    startCommand: |
      php artisan serve --host=0.0.0.0 --port=8000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      
      # Database configuration
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: gateway01.us-west-2.prod.aws.tidbcloud.com
      - key: DB_PORT
        value: "4000"
      - key: DB_DATABASE
        value: test
      - key: DB_USERNAME
        value: 3Y88Pry6Vd25MD5.root
      - key: DB_PASSWORD
        sync: false
