services:
  - type: web
    name: my-laravel-app
    runtime: docker
    dockerfilePath: Dockerfile
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan optimize:clear
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      
      # Database Configuration
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: gateway01.us-west-2.prod.aws.tidbcloud.com
      - key: DB_PORT
        value: "4000"
      - key: DB_DATABASE
        value: test
      - key: DB_USERNAME
        value: 3Y88Pry6Vd25MD5.root
      - key: DB_PASSWORD
        sync: false
      
      # SSL Configuration
      - key: MYSQL_ATTR_SSL_CA
        value: /etc/ssl/certs/ca-certificates.crt
      - key: MYSQL_ATTR_SSL_VERIFY_SERVER_CERT
        value: "true"
